name: Deploy Infrastructure


on:
  push:
    branches: [ "main" ]
    paths: ["infrastructure/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["infrastructure/**"]


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    name: Infrastructure Deploy
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Validate
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: validate
          name: validate-infrastructure
          scope: subscription
          location: uksouth
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./azure/main.bicep
      - name: Deploy
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: deploy-infrastructure
          scope: subscription
          location: uksouth
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./azure/main.bicep
